- name: Manage Pi-hole local DNS
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../vars/pihole.yml

  roles:
    - role: sbarbett.pihole.manage_local_records
    - role: sbarbett.pihole.manage_lists
